### ISSUE TITLE
您好，为啥server/typing被ignore了呀

### ISSUE THREAD

**Issue by tc93025** [GaryChangCN/kindle-comic-download#1]
![image](https://user-images.githubusercontent.com/65344481/98350752-bae86200-2056-11eb-9e35-3b26bf44541b.png)
想看看逻辑自己写一个，可以求一个typing里的东西嘛

**Comment by GaryChangCN** [comment]
这个项目并没有这个文件夹。  这个忽略规则时默认生成的，  ts 也早不用这个路径来放类型文件了
